services:
  postgrest:
    image: postgrest/postgrest:latest
    environment:
      - PGRST_DB_URI=${PGRST_DB_URI}
      - PGRST_DB_SCHEMA=public
      - PGRST_DB_ANON_ROLE=${PGRST_DB_ANON_ROLE}
      - PGRST_OPENAPI_SERVER_PROXY_URI=http://localhost:3000
    ports:
      - "3000:3000"

  postgrest-swagger:
    image: swaggerapi/swagger-ui
    environment:
      API_URL: http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      postgrest:
        condition: service_started
