"""create settlement table

Revision ID: 510fefd7eed4
Revises: af1d4726a84d
Create Date: 2024-10-17 10:27:32.856547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '510fefd7eed4'
down_revision: Union[str, None] = 'af1d4726a84d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'settlement',
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('next_day', sa.BigInteger(), nullable=True),
        sa.Column('after_next', sa.BigInteger(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlement')
    # ### end Alembic commands ###